name: mpd_docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - shapely
  - fiona
  - pyproj
  - libgdal
  - geotiff
  - libspatialite
  - matplotlib
  - gdal
  - hdf5
  - pip
  - sphinx
  - pydata-sphinx-theme